#!/bin/env perl
$|=1;
use strict;
use JSON;

my($docket) = @ARGV;
unless ($docket) {
	print "Usage: docket_overview <path to docket>\n";
	exit;
}

die "$docket doesn't look like a docket\n" unless looks_like_a_docket($docket);
my $data_dir = "$docket/data";
my $an_dir = "$docket/analyses";
my $fp_dir = "$docket/fingerprints";
my $cmp_dir = "$docket/comparisons";
my $viz_dir = "$docket/visualizations";

# get summary details
my $rows_hist = read_json("$data_dir/rows_hist.json.gz");
my $cols_hist = read_json("$data_dir/cols_hist.json.gz");
my $nrows = scalar keys %$rows_hist;
my $ncols = scalar keys %$cols_hist;

# get info on columns
my $col_info = read_json("$data_dir/cols_types.json.gz");
my($empty_cols, $num_cols);
foreach (keys %$col_info) {
	$col_info->{$_}{'values'}-- if $col_info->{$_}{'NULL'};
	$empty_cols++ if $col_info->{$_}{'NULL'} == $nrows;
	if ($col_info->{$_}{'NUM'} && !$col_info->{$_}{'STR'}) {
		$num_cols++;
	}
}
$empty_cols ||= 'zero';
$num_cols ||= 'zero';

# get info on correlations
my($num_corr_headers, $num_corr) = read_table("$cmp_dir/num_assoc.gz");
my($cat_corr_headers, $cat_corr) = read_table("$cmp_dir/cat_assoc.gz");
my $overviews = [['<a href="data_overview.png"><img src="data_overview.png" style="max-width:500px"></a>',
'<a href="data_overview_nullsorted.png"><img src="data_overview_nullsorted.png" style="max-width:500px"></a>']];

print_header("docket overview");
print_section("Overview", [
	"Docket path: $docket",
	join(" ", "Table size:", $nrows, "rows", "x", $ncols, "columns", "($empty_cols of which are empty, $num_cols are numerical)"),
	[$overviews, 'table', ['original', 'null-sorted']],
	]);


print_section("Columns", [
	[$col_info, 'table', undef, {'values' => 'distinct non-NULL values'}],
	]);

print_section("Associations", [
	[$num_corr, 'table', $num_corr_headers, {}, 5, 20],
	[$cat_corr, 'table', $cat_corr_headers, {}, -5, 20],
	]);

print_footer();





#########################
sub print_header {
	my($title) = @_;
	
	print "<!doctype html public \"-//w3c//dtd html 4.0 transitional//en\">\n";
	print "<html>\n<head>\n";
	print "  <title>$title</title>\n" if $title;
	print "</head>\n<body>\n";
}

sub print_footer {
	#my() = @_;
	
	print "</body>\n</html>\n";
}

sub print_section {
	my($heading, $content) = @_;
	
	print "  <h2>$heading</h2>\n";
	if (ref($content) eq 'ARRAY') {
		print_block($_) foreach @$content;
	} elsif (ref($content) eq 'HASH') {
		foreach my $blockname (sort keys %$content) {
			print "    <h3>$blockname</h3>\n";
			print_block($content->{$blockname});
		}
	}
}

sub print_block {
	my($bl) = @_;
	
	if (ref($bl) eq 'ARRAY') {
		my($what, $format) = @$bl;
		if ($format eq 'table') {
			print_table(@$bl);
		}
	} elsif (ref($bl) eq 'HASH') {
		
	} else {
		print "$bl<br>\n";
	}
}

sub print_table {
	my($what, $format, $headers, $replace, $sortkey, $show) = @_;
	
	if (ref($what) eq 'HASH') {
		my @keys = sort keys %$what;
		my %cols;
		while (my($key, $v) = each %$what) {
			$cols{$_}++ foreach keys %$v;
		}
		my @cols = sort keys %cols;
		print "<table border>\n";
		print "<tr><th>", join("</th><th>", 'Column name', map {$replace->{$_} || $_} @cols), "</th></tr>\n";
		foreach my $key (@keys) {
			print "<tr><td>$key</td><td>";
			print join("</td><td>", map {$what->{$key}{$_} || " "} @cols);
		}
		print "</td></tr>\n";
		print "</table>\n";
	} elsif (ref($what) eq 'ARRAY') {
		my @cols = @$headers;
		print "<table border>\n";
		print "<tr><th>", join("</th><th>", map {$replace->{$_} || $_} @cols), "</th></tr>\n";
		if ($sortkey) {
			my $reverse;
			if ($sortkey<0) {
				$reverse = 1;
				$sortkey = -$sortkey-1;
				my @sorted = sort {$b->[$sortkey] <=> $a->[$sortkey]} @$what;
				$what = \@sorted;
			} else {
				$sortkey--;
				my @sorted = sort {$a->[$sortkey] <=> $b->[$sortkey]} @$what;
				$what = \@sorted;
			}
			
		}
		my $shown;
		foreach my $line (@$what) {
			print "<tr><td>";
			print join("</td><td>", @$line);
			$shown++;
			last if $shown>=$show;
		}
		print "</td></tr>\n";
		print "</table>\n";
	}
	
}

sub read_table {
	my($file) = @_;
	my(@headers, @table);
	
	if ($file =~ /\.gz$/) {
		open F, "gunzip -c $file |";
	} else {
		open F, $file;
	}
	while (<F>) {
		next if /^#/;
		chomp;
		@headers = split /\t/;
		last;
	}
	while (<F>) {
		chomp;
		my(@v) = split /\t/;
		push @table, \@v;
	}
	
	close F;
	return \@headers, \@table;
}




sub read_json {
	my($file) = @_;
	my $json;
	open J, "gunzip -c $file |";
	while (<J>) {
		chomp;
		$json .= $_;
	}
	close J;
	return decode_json($json);
}


sub looks_like_a_docket {
	my($dir) = @_;
	
	return 1 if
		-d $dir && 
		-d "$dir/analyses" && 
		-d "$dir/fingerprints" && 
		-d "$dir/comparisons" && 
		-d "$dir/visualizations";
}

